//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.17929
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schulung {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResource() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Schulung.MessageResource", typeof(MessageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deutschland: Neue Datenschutzministerin fordert PGP-Verschlüsselung für parlamentarischen Emailverkehr. ähnelt.
        /// </summary>
        internal static string GameEventCountry1 {
            get {
                return ResourceManager.GetString("GameEventCountry1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Russland ist empört über das Ausmaß der Spionage und beginnt mit der Suche nach Maulwürfen in den eigenen Reihen. ähnelt.
        /// </summary>
        internal static string GameEventCountry2 {
            get {
                return ResourceManager.GetString("GameEventCountry2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nach den Enthüllungen von Edward Snowden: China verstärkt seine Cyberabwehr und bereitet sich auf zukünftige Angriffe vor. ähnelt.
        /// </summary>
        internal static string GameEventCountry3 {
            get {
                return ResourceManager.GetString("GameEventCountry3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die China blockiert ausländische Zugriffe mit großer Firewall um innländische Firmen zu schützen. ähnelt.
        /// </summary>
        internal static string GameEventEconomy1 {
            get {
                return ResourceManager.GetString("GameEventEconomy1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deutsche Firmen setzten zunehmend auf eigene Cloudlösung. Nutzung von Dropbox und Google Drive geht zurück. ähnelt.
        /// </summary>
        internal static string GameEventEconomy2 {
            get {
                return ResourceManager.GetString("GameEventEconomy2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Viele Firmen setzen auf abgeschottete Inselsysteme für Forschungseinrichtungen um Leaks zu verhindern. ähnelt.
        /// </summary>
        internal static string GameEventEconomy3 {
            get {
                return ResourceManager.GetString("GameEventEconomy3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Goverment Shutdown! Ihr Budget wurde für ein Jahr verringert! ähnelt.
        /// </summary>
        internal static string GameEventGovermentShutdown {
            get {
                return ResourceManager.GetString("GameEventGovermentShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ihr Budget wurde für ein Jahr erweitert! ähnelt.
        /// </summary>
        internal static string GameEventIncreaseBudget {
            get {
                return ResourceManager.GetString("GameEventIncreaseBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Syrische Rebellen erstehen auf dem Schwarzmarkt Atomwaffen zum Schnäppchenpreis. Die Terrorgefahr steigt! ähnelt.
        /// </summary>
        internal static string GameEventTerror1 {
            get {
                return ResourceManager.GetString("GameEventTerror1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eins der berüchtigtesten Terroristencamps ist nun auch auf Facebook vertreten. Über 5000 Nutzern gefällt das... ähnelt.
        /// </summary>
        internal static string GameEventTerror2 {
            get {
                return ResourceManager.GetString("GameEventTerror2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Immer mehr Extremisten nutzen Wikipedia für die Verbreitung von Propagandamaterial. ähnelt.
        /// </summary>
        internal static string GameEventTerror3 {
            get {
                return ResourceManager.GetString("GameEventTerror3", resourceCulture);
            }
        }
    }
}
